apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-mmldhwyt
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/go-mmldhwyt:a8dfbc55f2769e5d32c67e3f8b7b677403c55065@sha256:b37049690c3433ccf52f5970ea235273a3cb6120cacfe09a09e866db9b486372
          name: container-image
